import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowDownRight, ArrowUpRight, Award, BookOpen, BrainCircuit, Check, ChevronRight, CloudCog, Code2, Database, Github, GraduationCap, Linkedin, Mail, MapPin, Menu, Network, Send, ShieldCheck, Sparkles, Terminal, X } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Vamsi Krishna — AI & Software Developer" },
    { name: "description", content: "Portfolio of Vamsi Krishna, a B.Tech CSE student specializing in AI and Data Science." },
    { property: "og:title", content: "Vamsi Krishna — AI & Software Developer" },
    { property: "og:description", content: "An aspiring software developer exploring AI, data science, web development, Java, Python, and cybersecurity." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: Portfolio,
});

const nav = [["home","Home"],["about","About"],["education","Education"],["skills","Skills"],["projects","Projects"],["certifications","Certifications"],["learning","Learning"],["contact","Contact"]] as const;
const roles = ["Java Developer", "Web Developer", "Python Enthusiast", "AI Enthusiast", "Future Software Engineer"];
const education = [
  { years: "2024 — 2028", title: "B.Tech — Artificial Intelligence & Data Science", place: "Sree Venkateswara College of Engineering", note: "Current · Nellore, Andhra Pradesh" },
  { years: "2022 — 2024", title: "Intermediate / Higher Secondary", place: "Sree Chaitanya Inter College", note: "Completed" },
  { years: "2012 — 2022", title: "School Education", place: "Kendriya Vidyalaya (KV)", note: "Completed" },
];
const skillGroups = [
  { title: "Programming", icon: Code2, skills: ["Java", "Python"] },
  { title: "Web Development", icon: Terminal, skills: ["Front-End Development", "Web Development"] },
  { title: "Artificial Intelligence", icon: BrainCircuit, skills: ["Artificial Intelligence", "AI Tools"] },
  { title: "Cybersecurity & Cloud", icon: ShieldCheck, skills: ["Cybersecurity", "Cloud Security", "Zscaler Zero Trust Exchange"] },
];
const certificates = [
  ["Cybersecurity", "Cybersecurity"], ["AI Tools and ChatGPT Workshop", "Artificial Intelligence"],
  ["Full Stack Web Development with AI Training", "Web Development"], ["Cybersecurity Virtual Internship", "Virtual Internship"],
  ["Zero Trust Cloud Security Virtual Internship", "Cloud Security"],
];
const learning = [
  [BrainCircuit,"Artificial Intelligence","Exploring intelligent systems and practical AI tools"], [Database,"Data Science","Building foundations in data-led problem solving"],
  [Code2,"Java Development","Strengthening object-oriented programming skills"], [Terminal,"Python","Practicing versatile, readable programming"],
  [Network,"Web Development","Creating useful, responsive web experiences"], [Sparkles,"AI Tools","Learning modern AI-assisted workflows"],
  [CloudCog,"Cloud Technologies","Understanding modern cloud and Zero Trust concepts"], [ShieldCheck,"Cybersecurity","Developing security-first thinking"],
] as const;

function scrollTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); }

function Portfolio() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [active, setActive] = useState("home");
  const [role, setRole] = useState(0);
  const [sent, setSent] = useState(false);
  const [activeLearning, setActiveLearning] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setRole((v) => (v + 1) % roles.length), 2300); return () => window.clearInterval(timer); }, []);
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) setActive(entry.target.id); }), { rootMargin: "-35% 0px -55%" });
    nav.forEach(([id]) => { const node = document.getElementById(id); if (node) observer.observe(node); });
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) entry.target.classList.add("is-visible"); }), { threshold: 0.12 });
    document.querySelectorAll("[data-reveal]").forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const subject = String(data.get("subject") ?? "Portfolio enquiry").slice(0, 100);
    const body = `Hi Vamsi,\n\n${String(data.get("message") ?? "").slice(0, 1000)}\n\nFrom: ${String(data.get("name") ?? "").slice(0, 80)} (${String(data.get("email") ?? "").slice(0, 254)})`;
    setSent(true); window.location.href = `mailto:vamsikrishnakuracha30091@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };
  const selectedLearning = learning[activeLearning] ?? learning[0];
  const [SelectedLearningIcon, selectedLearningTitle, selectedLearningText] = selectedLearning;

  return <main className="min-h-screen bg-background text-foreground">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-border bg-background/80 backdrop-blur-xl">
      <div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 lg:px-8">
        <button onClick={() => scrollTo("home")} className="flex items-center gap-3" aria-label="Go to home">
          <span className="grid size-9 place-items-center rounded-md bg-primary font-bold text-primary-foreground">VK</span><span className="hidden text-sm font-semibold tracking-wide sm:block">VAMSI KRISHNA</span>
        </button>
        <nav className="hidden items-center gap-6 lg:flex" aria-label="Main navigation">{nav.map(([id,label]) => <button key={id} onClick={() => scrollTo(id)} className={`text-xs font-medium transition-colors ${active === id ? "text-primary" : "text-muted-foreground hover:text-foreground"}`}>{label}</button>)}</nav>
        <div className="flex items-center gap-2"><Button onClick={() => scrollTo("contact")} className="hidden sm:inline-flex">Let’s Connect <ArrowUpRight /></Button><Button variant="outline" size="icon" className="lg:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X/> : <Menu/>}</Button></div>
      </div>
      {menuOpen && <nav className="border-t border-border bg-background px-5 py-4 lg:hidden">{nav.map(([id,label]) => <button key={id} onClick={() => { scrollTo(id); setMenuOpen(false); }} className="block w-full border-b border-border py-3 text-left text-sm text-muted-foreground last:border-0">{label}</button>)}</nav>}
    </header>

    <section id="home" className="relative flex min-h-[92vh] scroll-mt-20 items-center overflow-hidden pt-24">
      <div className="hero-ambient pointer-events-none absolute inset-0" />
      <div className="tech-grid pointer-events-none absolute inset-0 opacity-55" />
      <div className="pointer-events-none absolute left-1/2 top-1/2 size-[34rem] -translate-x-1/2 -translate-y-1/2 rounded-full border border-primary/10 sm:size-[44rem]" />
      <div className="pointer-events-none absolute left-1/2 top-1/2 size-[25rem] -translate-x-1/2 -translate-y-1/2 rounded-full border border-accent/10 sm:size-[34rem]" />
      <div className="relative mx-auto w-full max-w-6xl px-5 py-14 text-center lg:px-8">
        <div className="mx-auto flex max-w-4xl flex-col items-center">
          <div className="hero-glass relative mb-6 grid size-24 place-items-center overflow-hidden rounded-full animate-profile sm:size-28">
            <img src="https://i.postimg.cc/02fWCLfM/Whats-App-Image-2026-09-08-at-22-42-42.jpg" alt="Kuracha Vamsi Krishna" className="size-full object-cover" loading="eager" />
            <span className="absolute -bottom-1 -right-1 grid size-8 place-items-center rounded-full border-4 border-background bg-primary text-primary-foreground"><Sparkles size={13}/></span>
          </div>
          <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-border bg-surface/70 px-4 py-2 text-[11px] font-medium uppercase tracking-[.16em] text-muted-foreground backdrop-blur-lg">
            <span className="relative flex size-2"><span className="absolute inline-flex size-full animate-ping rounded-full bg-primary opacity-70"/><span className="relative inline-flex size-2 rounded-full bg-primary"/></span>
            Open to learning, building & opportunities
          </div>
          <p className="mb-3 text-xs font-semibold uppercase tracking-[.24em] text-primary">Hello, I’m</p>
          <h1 className="font-display text-6xl font-extrabold leading-[.95] tracking-normal sm:text-7xl lg:text-8xl">Vamsi <span className="text-sheen">Krishna</span></h1>
          <div className="mt-6 flex min-h-8 items-center justify-center font-mono text-base text-muted-foreground sm:text-lg"><span className="mr-3 text-primary">//</span><span key={role} className="animate-fade-in">{roles[role]}</span><span className="ml-1 h-5 w-0.5 bg-primary animate-caret"/></div>
          <p className="mt-6 max-w-2xl text-base leading-8 text-muted-foreground sm:text-lg">A Computer Science Engineering student specializing in <span className="font-medium text-foreground">Artificial Intelligence & Data Science</span>—building practical technology solutions and growing through code.</p>
          <div className="mt-9 flex w-full flex-col justify-center gap-3 sm:w-auto sm:flex-row"><Button size="lg" className="h-12 rounded-full px-8 transition-transform hover:-translate-y-0.5" onClick={() => scrollTo("projects")}>Explore My Work <ArrowDownRight/></Button><Button size="lg" variant="outline" className="h-12 rounded-full bg-background/30 px-8 backdrop-blur-md" onClick={() => scrollTo("contact")}>Let’s Connect</Button></div>
          <div className="mt-8 flex items-center gap-3"><a className="grid size-10 place-items-center rounded-full border border-border bg-background/30 text-muted-foreground backdrop-blur-md transition hover:-translate-y-0.5 hover:border-primary/50 hover:text-primary" href="mailto:vamsikrishnakuracha30091@gmail.com" aria-label="Email Vamsi"><Mail size={17}/></a><span className="grid size-10 cursor-not-allowed place-items-center rounded-full border border-border bg-background/30 text-muted-foreground/40" title="LinkedIn URL coming soon"><Linkedin size={17}/></span><span className="grid size-10 cursor-not-allowed place-items-center rounded-full border border-border bg-background/30 text-muted-foreground/40" title="GitHub URL coming soon"><Github size={17}/></span></div>
          <div className="mt-11 h-px w-full max-w-2xl glow-line opacity-40" />
          <div className="mt-6 flex flex-wrap justify-center gap-x-8 gap-y-3 font-mono text-[11px] uppercase tracking-[.16em] text-muted-foreground/60"><span>Java</span><span>Python</span><span>Web Development</span><span>Artificial Intelligence</span></div>
        </div>
      </div>
      <div className="absolute bottom-6 left-1/2 hidden -translate-x-1/2 items-center gap-3 text-[10px] uppercase tracking-[.2em] text-muted-foreground/40 sm:flex"><span className="h-px w-8 bg-border"/> Scroll to explore <span className="h-px w-8 bg-border"/></div>
    </section>

    <Section id="about" eyebrow="01 / ABOUT" title="Curious by nature. Building with purpose." intro="A student-led journey shaped by thoughtful learning, practical creation, and a clear ambition to grow.">
      <div className="grid items-stretch gap-8 lg:grid-cols-[.72fr_1.28fr]" data-reveal><div className="glass-panel group relative min-h-[32rem] overflow-hidden rounded-lg"><div className="tech-grid absolute inset-0 opacity-70"/><div className="absolute inset-x-8 top-8 flex items-center justify-between font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground"><span>Profile / 2026</span><span className="flex items-center gap-2"><span className="size-1.5 rounded-full bg-primary"/>Student</span></div><div className="absolute inset-0 grid place-items-center"><div className="relative grid size-52 place-items-center rounded-full border border-primary/25 bg-primary/5 transition duration-500 group-hover:scale-105"><div className="absolute inset-4 rounded-full border border-accent/20"/><span className="font-display text-7xl font-bold text-sheen">VK</span></div></div><div className="absolute inset-x-0 bottom-0 border-t border-border bg-background/65 p-5 text-center backdrop-blur-xl"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-primary">Portrait placeholder</p><p className="mt-2 text-xs text-muted-foreground">A professional photo can be added here</p></div></div>
        <div className="flex flex-col justify-between rounded-lg border border-border bg-surface/45 p-7 sm:p-10"><div><span className="inline-flex items-center gap-2 font-mono text-xs text-primary"><Terminal size={14}/> ABOUT_ME.md</span><p className="mt-7 max-w-3xl text-lg leading-8 text-muted-foreground sm:text-xl">I’m pursuing a B.Tech in <span className="text-foreground">Artificial Intelligence and Data Science</span> at Sree Venkateswara College of Engineering. I’m developing practical foundations across web development, Java, Python, AI, cybersecurity, and cloud security—one project and concept at a time.</p><p className="mt-5 max-w-3xl leading-7 text-muted-foreground">I’m driven by how technology can turn ideas into useful solutions. My goal is simple: keep learning, build thoughtfully, and grow into a capable software engineer.</p></div>
          <div className="mt-10 grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-4">{[["2024–2028","B.Tech Journey"],["AI & Data Science","Specialization"],["Web Development","Primary Interest"],["AI & Cybersecurity","Tech Interests"]].map(([a,b],i)=><div key={b} className="group/stat bg-background/70 p-5 transition hover:bg-surface-strong"><span className="font-mono text-[10px] text-muted-foreground/50">0{i+1}</span><p className="mt-4 text-sm font-semibold text-primary">{a}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{b}</p></div>)}</div>
        </div></div>
    </Section>

    <Section id="education" eyebrow="02 / EDUCATION" title="A foundation for what comes next." intro="From school fundamentals to a focused degree in AI and Data Science." muted>{<div className="relative mx-auto max-w-5xl" data-reveal><div className="absolute bottom-12 left-[1.15rem] top-12 w-px glow-line opacity-60 sm:left-1/2"/>{education.map((item,i)=><article key={item.years} className={`relative mb-6 grid sm:grid-cols-2 ${i % 2 ? "sm:[&>div]:col-start-2" : ""}`}><span className="absolute left-[.72rem] top-8 z-10 grid size-4 place-items-center rounded-full border border-primary bg-background shadow-[0_0_18px_var(--primary)] sm:left-1/2 sm:-translate-x-1/2"><span className="size-1 rounded-full bg-primary"/></span><div className={`${i % 2 ? "ml-12 sm:ml-8" : "ml-12 sm:mr-8 sm:ml-0"} glass-panel rounded-lg p-6 transition duration-300 hover:-translate-y-1 hover:border-primary/35`}><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-mono text-xs text-primary">{item.years}</p>{i===0 && <span className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-[10px] uppercase tracking-[.12em] text-primary"><span className="size-1.5 rounded-full bg-primary"/> In progress</span>}</div><GraduationCap className="mt-7 text-primary" size={26}/><h3 className="mt-4 text-xl font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.place}</p><p className="mt-4 font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground/60">{item.note}</p></div></article>)}</div>}
    </Section>

    <Section id="skills" eyebrow="03 / SKILLS" title="Tools I’m learning to build with." intro="An evolving toolkit across software, intelligent systems, and secure cloud thinking."><div className="grid gap-4 md:grid-cols-2" data-reveal>{skillGroups.map(({title,icon:Icon,skills},i)=><article key={title} className="glass-panel group relative min-h-64 overflow-hidden rounded-lg p-7 transition duration-300 hover:-translate-y-1 hover:border-primary/40"><span className="absolute right-6 top-5 font-display text-6xl font-bold text-foreground/[.035]">0{i+1}</span><div className="flex items-center gap-4"><span className="grid size-12 place-items-center rounded-md border border-primary/15 bg-primary/10 text-primary transition group-hover:bg-primary group-hover:text-primary-foreground"><Icon size={22}/></span><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Skill group</p><h3 className="mt-1 text-lg font-semibold">{title}</h3></div></div><div className="mt-9 flex flex-wrap gap-2">{skills.map(s=><span key={s} className="rounded-md border border-border bg-background/55 px-3 py-2 text-sm text-muted-foreground transition group-hover:border-primary/20 group-hover:text-foreground">{s}</span>)}</div><div className="absolute inset-x-0 bottom-0 h-px glow-line opacity-0 transition group-hover:opacity-70"/></article>)}</div></Section>

    <Section id="projects" eyebrow="04 / FEATURED PROJECTS" title="The strongest work is still being built." intro="A dedicated space for practical work as ideas move from learning to working software." muted><div className="glass-panel relative overflow-hidden rounded-lg" data-reveal><div className="tech-grid absolute inset-0 opacity-70"/><div className="relative grid min-h-[34rem] lg:grid-cols-[1.2fr_.8fr]"><div className="flex flex-col justify-between border-b border-border p-8 sm:p-12 lg:border-b-0 lg:border-r"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.16em] text-primary"><span className="size-1.5 rounded-full bg-primary"/> Portfolio in progress</span><span className="font-mono text-xs text-muted-foreground/50">001</span></div><div className="py-16"><span className="mb-7 grid size-16 place-items-center rounded-md border border-primary/20 bg-primary/10 text-primary"><Terminal size={28}/></span><h3 className="max-w-2xl text-2xl font-semibold leading-tight sm:text-4xl">Building practical projects and continuously expanding my development portfolio.</h3><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">Real projects will appear here with visuals, concise problem statements, technology stacks, repository links, and live demos as they are completed.</p></div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground/50">No project details have been invented</p></div><div className="grid grid-cols-2 bg-background/35">{[["Project image","Visual preview"],["Project name","Clear identity"],["Technologies","Tools used"],["GitHub + Demo","Working links"]].map(([title,text],i)=><div key={title} className="group flex min-h-52 flex-col justify-between border-b border-r border-border p-6 transition hover:bg-surface-strong"><span className="font-mono text-xs text-primary/60">0{i+1}</span><div><p className="font-medium">{title}</p><p className="mt-2 text-xs text-muted-foreground">{text}</p></div><ArrowUpRight className="self-end text-muted-foreground/30 transition group-hover:text-primary" size={18}/></div>)}</div></div></div></Section>

    <Section id="certifications" eyebrow="05 / CERTIFICATIONS" title="Learning beyond the classroom." intro="Focused programs and virtual experiences supporting a broader technical foundation."><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3" data-reveal>{certificates.map(([title,cat],i)=><article key={title} className={`glass-panel group flex min-h-72 flex-col rounded-lg p-6 transition duration-300 hover:-translate-y-1 hover:border-primary/35 ${i===0 ? "lg:col-span-2" : ""}`}><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-md bg-primary/10 text-primary"><Award size={21}/></span><span className="font-mono text-xs text-muted-foreground/50">CERT / 0{i+1}</span></div><p className="mt-8 font-mono text-[10px] uppercase tracking-[.16em] text-primary">{cat}</p><h3 className="mt-3 max-w-xl text-xl font-semibold leading-7">{title}</h3><div className="mt-auto flex items-end justify-between gap-4 pt-8"><div className="text-xs leading-5 text-muted-foreground"><p>Organization — not provided</p><p>Date — not provided</p></div><span className="grid size-9 place-items-center rounded-md border border-border text-muted-foreground/40" title="Certificate link coming soon"><ChevronRight size={16}/></span></div></article>)}</div></Section>

    <Section id="learning" eyebrow="06 / CURRENTLY EXPLORING" title="Learn → Build → Innovate → Grow" intro="A living roadmap of the areas shaping my development right now." muted><div className="grid overflow-hidden rounded-lg border border-border bg-surface/50 lg:grid-cols-[.9fr_1.1fr]" data-reveal><div className="border-b border-border p-4 lg:border-b-0 lg:border-r">{learning.map(([Icon,title],i)=><button key={title} onClick={() => setActiveLearning(i)} className={`group flex w-full items-center gap-4 rounded-md px-4 py-4 text-left transition ${activeLearning === i ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-surface-strong hover:text-foreground"}`} aria-pressed={activeLearning === i}><span className="font-mono text-[10px] opacity-60">{String(i+1).padStart(2,"0")}</span><Icon size={18}/><span className="font-medium">{title}</span><ChevronRight size={15} className="ml-auto transition group-hover:translate-x-0.5"/></button>)}</div><div className="relative flex min-h-[31rem] flex-col justify-between overflow-hidden p-8 sm:p-12"><div className="tech-grid absolute inset-0 opacity-50"/><div className="relative"><span className="font-mono text-xs uppercase tracking-[.16em] text-primary">Current focus / {String(activeLearning+1).padStart(2,"0")}</span><SelectedLearningIcon className="mt-16 text-primary" size={48}/><h3 className="mt-7 font-display text-3xl font-semibold sm:text-5xl">{selectedLearningTitle}</h3><p className="mt-5 max-w-xl text-lg leading-8 text-muted-foreground">{selectedLearningText}.</p></div><div className="relative mt-12"><div className="mb-4 flex justify-between font-mono text-[10px] uppercase tracking-[.14em] text-muted-foreground"><span>Learning</span><span>Building foundations</span></div><div className="h-px glow-line"/></div></div></div></Section>

    <Section id="contact" eyebrow="07 / CONTACT" title="Let’s build something together." intro="Open to internships, collaboration, hackathons, learning opportunities, and conversations around technology."><div className="glass-panel grid overflow-hidden rounded-lg lg:grid-cols-[.8fr_1.2fr]" data-reveal><div className="relative border-b border-border bg-surface/60 p-7 sm:p-10 lg:border-b-0 lg:border-r"><div className="tech-grid absolute inset-0 opacity-40"/><div className="relative"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">Start a conversation</p><h3 className="mt-5 text-2xl font-semibold">Have an idea or opportunity in mind?</h3><p className="mt-4 max-w-md leading-7 text-muted-foreground">I’d be glad to hear from you and learn more.</p><div className="mt-10 space-y-4"><a href="mailto:vamsikrishnakuracha30091@gmail.com" className="group flex items-start gap-4 rounded-md border border-border bg-background/45 p-4 text-sm transition hover:border-primary/35"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-primary/10 text-primary"><Mail size={18}/></span><span><small className="block text-muted-foreground">Email</small><span className="mt-1 block break-all group-hover:text-primary">vamsikrishnakuracha30091@gmail.com</span></span></a><div className="flex items-start gap-4 rounded-md border border-border bg-background/45 p-4 text-sm"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-primary/10 text-primary"><MapPin size={18}/></span><span><small className="block text-muted-foreground">Location</small><span className="mt-1 block">Nellore, Andhra Pradesh, India</span></span></div><div className="flex items-start gap-4 rounded-md border border-border bg-background/25 p-4 text-sm opacity-60"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-muted"><Linkedin size={18}/></span><span><small className="block text-muted-foreground">LinkedIn</small><span className="mt-1 block">Kuracha Vamsi Krishna · URL coming soon</span></span></div></div></div></div>
        <form onSubmit={submit} className="grid gap-5 bg-background/30 p-7 sm:grid-cols-2 sm:p-10"><div className="mb-2 sm:col-span-2"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">Message form</p><p className="mt-2 text-sm text-muted-foreground">This opens a ready-to-send draft in your email app.</p></div><Field label="Name" name="name" placeholder="Your name"/><Field label="Email" name="email" type="email" placeholder="you@example.com"/><Field label="Subject" name="subject" placeholder="What would you like to discuss?" wide/><label className="grid gap-2 text-sm sm:col-span-2">Message<textarea name="message" required minLength={10} maxLength={1000} rows={6} placeholder="Tell me about the opportunity..." className="resize-none rounded-md border border-input bg-background/60 px-4 py-3 text-sm outline-none transition placeholder:text-muted-foreground/60 focus:border-primary focus:ring-2 focus:ring-primary/15"/></label><div className="flex flex-wrap items-center gap-4 sm:col-span-2"><Button size="lg" type="submit" className="h-12 rounded-full px-7">Send Message <Send/></Button>{sent && <span className="flex items-center gap-2 text-sm text-primary"><Check size={16}/> Email draft opened</span>}</div></form>
      </div></Section>
    <footer className="border-t border-border px-5 py-10"><div className="mx-auto grid max-w-7xl items-center gap-7 text-center sm:grid-cols-3 sm:text-left"><div className="flex items-center justify-center gap-3 sm:justify-start"><span className="grid size-9 place-items-center rounded-md bg-primary font-bold text-primary-foreground">VK</span><div><p className="text-sm font-semibold">VAMSI KRISHNA</p><p className="mt-1 text-[10px] text-muted-foreground">© 2026 · All rights reserved.</p></div></div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground sm:text-center">Learn → Build → Innovate → Grow</div><div className="flex items-center justify-center gap-4 text-muted-foreground sm:justify-end"><span className="mr-2 hidden text-xs lg:inline">Built with curiosity, code & AI.</span><a href="mailto:vamsikrishnakuracha30091@gmail.com" aria-label="Email" className="transition hover:text-primary"><Mail size={17}/></a><Linkedin size={17} className="opacity-35"/><Github size={17} className="opacity-35"/></div></div></footer>
  </main>;
}

function Section({id,eyebrow,title,intro,children,muted=false}:{id:string;eyebrow:string;title:string;intro?:string;children:React.ReactNode;muted?:boolean}) { return <section id={id} className={`section-field relative scroll-mt-20 overflow-hidden px-5 py-24 sm:py-32 lg:px-8 ${muted ? "bg-muted/35" : ""}`}><div className="pointer-events-none absolute inset-0 section-grid"/><div className="relative mx-auto max-w-7xl"><div className="mb-12 grid gap-5 lg:grid-cols-[1fr_.7fr] lg:items-end" data-reveal><div><p className="font-mono text-xs tracking-[.2em] text-primary">{eyebrow}</p><h2 className="mt-4 max-w-3xl font-display text-3xl font-semibold leading-tight tracking-normal sm:text-5xl">{title}</h2></div>{intro && <p className="max-w-xl text-sm leading-7 text-muted-foreground lg:justify-self-end">{intro}</p>}</div>{children}</div></section>; }
function Field({label,name,placeholder,type="text",wide=false}:{label:string;name:string;placeholder:string;type?:string;wide?:boolean}) { return <label className={`grid gap-2 text-sm ${wide ? "sm:col-span-2" : ""}`}>{label}<input name={name} type={type} required maxLength={type === "email" ? 254 : 100} placeholder={placeholder} className="h-12 rounded-md border border-input bg-background/60 px-4 text-sm outline-none transition placeholder:text-muted-foreground/60 focus:border-primary focus:ring-2 focus:ring-primary/15"/></label>; }
